// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVJGgUo5Qx_3Rk8oJfswJCgOAokU4i4yg',
    appId: '1:1039927889428:web:8d9057a117d4f318a2a101',
    messagingSenderId: '1039927889428',
    projectId: 'dearfam-1e2fe',
    authDomain: 'dearfam-1e2fe.firebaseapp.com',
    storageBucket: 'dearfam-1e2fe.firebasestorage.app',
    measurementId: 'G-KX0W9G9LSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7oC0uS2vKt_EiqF6DkKqHctrrL4FGWio',
    appId: '1:1039927889428:android:8f446fcdf8ef5ecba2a101',
    messagingSenderId: '1039927889428',
    projectId: 'dearfam-1e2fe',
    storageBucket: 'dearfam-1e2fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_PSauToF2vtJ__7q0-_dahfYa6Pe0WhA',
    appId: '1:1039927889428:ios:4a0870ea4261bbd7a2a101',
    messagingSenderId: '1039927889428',
    projectId: 'dearfam-1e2fe',
    storageBucket: 'dearfam-1e2fe.firebasestorage.app',
    iosBundleId: 'com.example.dearfam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_PSauToF2vtJ__7q0-_dahfYa6Pe0WhA',
    appId: '1:1039927889428:ios:4a0870ea4261bbd7a2a101',
    messagingSenderId: '1039927889428',
    projectId: 'dearfam-1e2fe',
    storageBucket: 'dearfam-1e2fe.firebasestorage.app',
    iosBundleId: 'com.example.dearfam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVJGgUo5Qx_3Rk8oJfswJCgOAokU4i4yg',
    appId: '1:1039927889428:web:b89c290061657fd5a2a101',
    messagingSenderId: '1039927889428',
    projectId: 'dearfam-1e2fe',
    authDomain: 'dearfam-1e2fe.firebaseapp.com',
    storageBucket: 'dearfam-1e2fe.firebasestorage.app',
    measurementId: 'G-EWLJEYQXGM',
  );
}
